# Generated by Django 4.1 on 2022-08-21 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(choices=[('Port Blair', 'Port Blair'), ('Adoni', 'Adoni'), ('Amaravati', 'Amaravati'), ('Anantapur', 'Anantapur'), ('Chandragiri', 'Chandragiri'), ('Chittoor', 'Chittoor'), ('Dowlaiswaram', 'Dowlaiswaram'), ('Eluru', 'Eluru'), ('Guntur', 'Guntur'), ('Kadapa', 'Kadapa'), ('Kakinada', 'Kakinada'), ('Kurnool', 'Kurnool'), ('Machilipatnam', 'Machilipatnam'), ('Nagarjunakoṇḍa', 'Nagarjunakoṇḍa'), ('Rajahmundry', 'Rajahmundry'), ('Srikakulam', 'Srikakulam'), ('Tirupati', 'Tirupati'), ('Vijayawada', 'Vijayawada'), ('Visakhapatnam', 'Visakhapatnam'), ('Vizianagaram', 'Vizianagaram'), ('Yemmiganur', 'Yemmiganur')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dentist',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.contact'),
        ),
    ]
