# Generated by Django 4.1 on 2022-08-21 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_city_dentist_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pin_code',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
