# Generated by Django 4.1 on 2022-08-21 05:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_id',
            field=models.CharField(max_length=128, null=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
