# Generated by Django 4.1 on 2022-08-21 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_id',
            field=models.CharField(max_length=128, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
