# Generated by Django 4.1 on 2022-08-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contact_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(choices=[('A', 'A'), ('n', 'n'), ('d', 'd'), ('a', 'a'), ('m', 'm'), ('a', 'a'), ('n', 'n'), (' ', ' '), ('&', '&'), (' ', ' '), ('N', 'N'), ('i', 'i'), ('c', 'c'), ('o', 'o'), ('b', 'b'), ('a', 'a'), ('r', 'r'), (' ', ' '), ('I', 'I'), ('s', 's'), ('l', 'l'), ('a', 'a'), ('n', 'n'), ('d', 'd'), ('s', 's'), ('A', 'A'), ('n', 'n'), ('d', 'd'), ('h', 'h'), ('r', 'r'), ('a', 'a'), (' ', ' '), ('P', 'P'), ('r', 'r'), ('a', 'a'), ('d', 'd'), ('e', 'e'), ('s', 's'), ('h', 'h')], max_length=64, null=True),
        ),
    ]
