# Generated by Django 4.1 on 2022-08-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='products',
            field=models.ManyToManyField(to='core.product'),
        ),
    ]
