# Generated by Django 4.1 on 2022-08-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_maker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='maker',
            field=models.ManyToManyField(blank=True, to='core.company'),
        ),
    ]
