# Generated by Django 4.1 on 2022-08-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_product_maker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='products',
        ),
        migrations.AddField(
            model_name='company',
            name='products',
            field=models.ManyToManyField(null=True, to='core.product'),
        ),
    ]
