# Generated by Django 4.1 on 2022-08-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_company_products_company_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='products',
            field=models.ManyToManyField(to='core.product'),
        ),
    ]
