# Generated by Django 4.1 on 2022-08-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_company_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maker',
            field=models.ManyToManyField(to='core.company'),
        ),
    ]
