# Generated by Django 4.1 on 2022-08-21 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_product_maker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='maker',
        ),
        migrations.AddField(
            model_name='product',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
    ]
