# Generated by Django 4.1 on 2022-08-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_dentist_inventory_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='inventory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inventory'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='core.dentist'),
        ),
    ]
