# Generated by Django 4.1 on 2022-08-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_inventory_items_inventory_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(to='core.item'),
        ),
    ]
