# Generated by Django 4.1 on 2022-08-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_dentist_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='list_price',
        ),
    ]
