# Generated by Django 4.1 on 2022-08-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('companies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company')),
                ('dentist', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.dentist')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.product')),
            ],
        ),
    ]
