# Generated by Django 4.1 on 2022-08-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='companies',
        ),
        migrations.AddField(
            model_name='auction',
            name='companies',
            field=models.ManyToManyField(null=True, to='core.company'),
        ),
    ]
