# Generated by Django 4.1 on 2022-08-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_auction_companies_auction_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='maker',
        ),
        migrations.AlterField(
            model_name='auction',
            name='companies',
            field=models.ManyToManyField(to='core.company'),
        ),
    ]
