# Generated by Django 4.1 on 2022-08-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_productbycompany_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbycompany',
            name='product',
        ),
        migrations.AddField(
            model_name='productbycompany',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.product'),
        ),
    ]
