# Generated by Django 4.1 on 2022-08-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_productbycompany_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('MG', 'Milligrams'), ('G', 'Grams'), ('ML', 'Milliliters'), ('M', 'Meters')], max_length=16),
        ),
        migrations.AlterField(
            model_name='productbycompany',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.company'),
        ),
    ]
