# Generated by Django 4.1 on 2022-08-22 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_product_unit_alter_productbycompany_maker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='dentist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.dentist'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.product'),
        ),
    ]
