# Generated by Django 4.1 on 2022-08-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_auction_dentist_alter_auction_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='auction',
            unique_together={('dentist', 'product')},
        ),
    ]
