# Generated by Django 4.1 on 2022-08-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_auction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(blank=True, to='core.item'),
        ),
    ]
