# Generated by Django 4.1 on 2022-08-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_inventory_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='products',
            field=models.ManyToManyField(blank=True, to='core.product'),
        ),
    ]
