# Generated by Django 4.1 on 2022-08-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_company_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.productbycompany'),
        ),
    ]
