# Generated by Django 4.1 on 2022-08-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_item_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.contact'),
        ),
    ]
