# Generated by Django 4.1 on 2022-08-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_company_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('MG', 'Milligrams'), ('G', 'Grams'), ('ML', 'Milliliters'), ('M', 'Meters'), ('NOS', 'Nos.')], max_length=16),
        ),
    ]
