# Generated by Django 4.1 on 2022-08-25 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_company_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email_id',
            field=models.CharField(max_length=128, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
