# Generated by Django 4.1 on 2022-08-25 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_contact_email_id_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='inventory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inventory'),
        ),
    ]
