# Generated by Django 4.1 on 2022-08-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auctionhistory_auction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auctions',
            field=models.ManyToManyField(to='core.auction'),
        ),
    ]
