# Generated by Django 4.1 on 2022-08-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_company_auctions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='history',
            field=models.ManyToManyField(blank=True, to='core.auctionhistory'),
        ),
    ]
