# Generated by Django 4.1 on 2022-08-27 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_auction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionhistory',
            name='auction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.auction'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='auction_history', to='core.auctionhistory'),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contact'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='core.dentist'),
        ),
    ]
