# Generated by Django 4.1 on 2022-08-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auctionhistory_auction_alter_auction_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionhistory',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
