# Generated by Django 4.1 on 2022-08-27 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_auctionhistory_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionhistory',
            name='bid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
    ]
