# Generated by Django 4.1 on 2022-08-28 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_auctionhistory_bid_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dentist')),
                ('items', models.ManyToManyField(to='core.item')),
            ],
        ),
    ]
