# Generated by Django 4.1 on 2022-08-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_company_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='company_order', to='core.order'),
        ),
    ]
