# Generated by Django 4.1 on 2022-08-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_dentist_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='dentist_order', to='core.order'),
        ),
    ]
