CITIES = [
    "Port Blair",
    "Adoni",
    "Amaravati",
    "Anantapur",
    "Chandragiri",
    "Chittoor",
    "Dowlaiswaram",
    "Eluru",
    "Guntur",
    "Kadapa",
    "Kakinada",
    "Kurnool",
    "Machilipatnam",
    "Nagarjunakoṇḍa",
    "Rajahmundry",
    "Srikakulam",
    "Tirupati",
    "Vijayawada",
    "Visakhapatnam",
    "Vizianagaram",
    "Yemmiganur",
]

STATE_MAP = {
    "Port Blair": "Andhra Pradesh",
    "Adoni": "Andhra Pradesh",
    "Amaravati": "Andhra Pradesh",
    "Anantapur": "Andhra Pradesh",
    "Chandragiri": "Andhra Pradesh",
    "Chittoor": "Andhra Pradesh",
    "Dowlaiswaram": "Andhra Pradesh",
    "Eluru": "Andhra Pradesh",
    "Guntur": "Andhra Pradesh",
    "Kadapa": "Andhra Pradesh",
    "Kakinada": "Andhra Pradesh",
    "Kurnool": "Andhra Pradesh",
    "Machilipatnam": "Andhra Pradesh",
    "Nagarjunakoṇḍa": "Andhra Pradesh",
    "Rajahmundry": "Andhra Pradesh",
    "Srikakulam": "Andhra Pradesh",
    "Tirupati": "Andhra Pradesh",
    "Vijayawada": "Andhra Pradesh",
    "Visakhapatnam": "Andhra Pradesh",
    "Vizianagaram": "Andhra Pradesh",
    "Yemmiganur": "Andhra Pradesh",
}